---
# Full pipeline: prepare openSUSE/SLE nodes + deploy k3s + install Cozystack
#
# Prerequisites:
#   ansible-galaxy collection install --requirements-file ../../requirements.yml
#
# Usage:
#   ansible-playbook site.yml

- name: Prepare openSUSE/SLE nodes for Cozystack
  ansible.builtin.import_playbook: prepare-suse.yml

- name: Deploy k3s cluster
  ansible.builtin.import_playbook: k3s.orchestration.site

- name: Install Cozystack
  ansible.builtin.import_playbook: cozystack.installer.site
